const employees = [
    {
        id: 0,
        prenom: "anas",
        nom: "ab",
        poste: "Agent agricole",
        matricule: "LJ390L",
        employeur: "Best Profile",
        cin: "EA22901",
        dateNaissance: "1999-03-22",
        nbEnfants: 3,
        etatCivil: "marié",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        debutContrat: "2023-07-20",
        finContrat: "2023-12-22",
        dateDebauche: "",
        salaire: 3000,
        contrat: "CI/CD",
        indemnité: 500,
        entiteAffectation: "Entité1",
        email: "anas@gmail.com",
        password: "123456",
        premierEmbauche: "mon premier embauche",
        activité: "Actif",
        sexe: "Homme",
    },
    {
        id: 1,
        prenom: "Sarah",
        nom: "Johnson",
        poste: "Technicien",
        matricule: "MJ470M",
        employeur: "UM6P",
        cin: "EB15782",
        dateNaissance: "1999-03-22",
        nbEnfants: 0,
        etatCivil: "célibataire",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        debutContrat: "2023-07-20",
        finContrat: "2023-12-22",
        dateDebauche: "",
        salaire: 4500,
        contrat: "CDI",
        indemnité: 300,
        entiteAffectation: "Technician Department",
        email: "sarah@example.com",
        password: "technician123",
        premierEmbauche: "First Hire",
        activité: "Actif",
        sexe: "Homme",
    },
    {
        id: 2,
        prenom: "Mohammed",
        nom: "Ali",
        poste: "Agent agricole",
        matricule: "BA789J",
        employeur: "Best Profile",
        cin: "BF21785",
        dateNaissance: "1999-03-22",
        nbEnfants: 1,
        etatCivil: "marié",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        debutContrat: "2023-07-20",
        finContrat: "2023-12-22",
        dateDebauche: "",
        salaire: 2800,
        contrat: "CI/CD",
        indemnité: 450,
        entiteAffectation: "Entité2",
        email: "mohammed@example.com",
        password: "agriculture123",
        premierEmbauche: "First Job",
        activité: "Actif",
        sexe: "Homme",
    },
    {
        id: 3,
        prenom: "Linda",
        nom: "Smith",
        poste: "Technicien",
        matricule: "LS602P",
        employeur: "UM6P",
        cin: "LC41903",
        dateNaissance: "1999-03-22",
        nbEnfants: 2,
        etatCivil: "marié",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        debutContrat: "2023-07-20",
        finContrat: "2023-12-22",
        dateDebauche: "",
        salaire: 4200,
        contrat: "CDD",
        indemnité: 350,
        entiteAffectation: "Technician Department",
        email: "linda@example.com",
        password: "smith123",
        premierEmbauche: "New Start",
        activité: "Actif",
        sexe: "Femme",
    },
    {
        id: 4,
        prenom: "Ahmed",
        nom: "Khan",
        poste: "Agent Agricole",
        matricule: "AK123Z",
        employeur: "Best Profile",
        cin: "AD85026",
        dateNaissance: "1999-03-22",
        nbEnfants: 2,
        etatCivil: "marié",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        debutContrat: "2023-07-20",
        finContrat: "2023-12-22",
        dateDebauche: "",
        salaire: 5500,
        contrat: "CDI",
        indemnité: 500,
        entiteAffectation: "Département Technique",
        email: "ahmed@example.com",
        password: "software123",
        premierEmbauche: "Première Expérience",
        activité: "Actif",
        sexe: "Homme",
    },
    {
        id: 5,
        prenom: "Emily",
        nom: "Brown",
        poste: "Technicien",
        matricule: "EB704K",
        employeur: "Best Profile",
        cin: "EF63219",
        dateNaissance: "1999-03-22",
        nbEnfants: 1,
        etatCivil: "marié",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        debutContrat: "2023-07-20",
        finContrat: "2023-12-22",
        dateDebauche: "",
        salaire: 4800,
        contrat: "CDD",
        indemnité: 300,
        entiteAffectation: "Département Développement Web",
        email: "emily@example.com",
        password: "frontend123",
        premierEmbauche: "Nouveau Défi",
        activité: "Inactif",
        sexe: "Femme",
    },
];
export default employees;
