const employees = [
    {
        id: 0,
        prenom: "anas",
        nom: "ab",
        poste: "Agent agricole",
        matricule: "LJ390L",
        employeur: "Best profile",
        cin: "EA22901",
        dateNaissance: "20/06/2001",
        nbEnfants: 3,
        etatCivile: "marié",
        cnss: "CNSS",
        dateEmbauche: "11/08/2023",
        finContrat: "11/09/2024",
        dateDebauche: "--",
        salaire: 3000,
        contrat: "CI/CD",
        indemnité: 500,
        entiteAffectation: "Entité1",
        email: "anas@gmail.com",
        password: "123456",
        premierEmbauche: "mon premier embauche",
    },
    {
        id: 1,
        prenom: "Sarah",
        nom: "Johnson",
        poste: "Technicien",
        matricule: "MJ470M",
        employeur: "UM6P",
        cin: "EB15782",
        dateNaissance: "15/03/1990",
        nbEnfants: 0,
        etatCivile: "célibataire",
        cnss: "CNSS",
        dateEmbauche: "01/05/2022",
        finContrat: "01/05/2023",
        dateDebauche: "--",
        salaire: 4500,
        contrat: "CDI",
        indemnité: 300,
        entiteAffectation: "Technician Department",
        email: "sarah@example.com",
        password: "technician123",
        premierEmbauche: "First Hire",
    },
    {
        id: 2,
        prenom: "Mohammed",
        nom: "Ali",
        poste: "Agent agricole",
        matricule: "BA789J",
        employeur: "Best profile",
        cin: "BF21785",
        dateNaissance: "12/08/1995",
        nbEnfants: 1,
        etatCivile: "marié",
        cnss: "CNSS",
        dateEmbauche: "20/07/2023",
        finContrat: "20/07/2024",
        dateDebauche: "--",
        salaire: 2800,
        contrat: "CI/CD",
        indemnité: 450,
        entiteAffectation: "Entité2",
        email: "mohammed@example.com",
        password: "agriculture123",
        premierEmbauche: "First Job",
    },
    {
        id: 3,
        prenom: "Linda",
        nom: "Smith",
        poste: "Technicien",
        matricule: "LS602P",
        employeur: "UM6P",
        cin: "LC41903",
        dateNaissance: "02/11/1988",
        nbEnfants: 2,
        etatCivile: "marié",
        cnss: "CNSS",
        dateEmbauche: "10/03/2023",
        finContrat: "10/03/2024",
        dateDebauche: "--",
        salaire: 4200,
        contrat: "CDD",
        indemnité: 350,
        entiteAffectation: "Technician Department",
        email: "linda@example.com",
        password: "smith123",
        premierEmbauche: "New Start",
    },
    {
        id: 4,
        prenom: "Ahmed",
        nom: "Khan",
        poste: "Agent Agricole",
        matricule: "AK123Z",
        employeur: "Best Profile",
        cin: "AD85026",
        dateNaissance: "08/12/1993",
        nbEnfants: 2,
        etatCivile: "marié",
        cnss: "CNSS",
        dateEmbauche: "05/02/2023",
        finContrat: "05/02/2024",
        dateDebauche: "--",
        salaire: 5500,
        contrat: "CDI",
        indemnité: 500,
        entiteAffectation: "Département Technique",
        email: "ahmed@example.com",
        password: "software123",
        premierEmbauche: "Première Expérience",
    },
    {
        id: 5,
        prenom: "Emily",
        nom: "Brown",
        poste: "Technicien",
        matricule: "EB704K",
        employeur: "Best Profile",
        cin: "EF63219",
        dateNaissance: "22/09/1992",
        nbEnfants: 1,
        etatCivile: "marié",
        cnss: "CNSS",
        dateEmbauche: "15/06/2022",
        finContrat: "15/06/2023",
        dateDebauche: "--",
        salaire: 4800,
        contrat: "CDD",
        indemnité: 300,
        entiteAffectation: "Département Développement Web",
        email: "emily@example.com",
        password: "frontend123",
        premierEmbauche: "Nouveau Défi",
    },
];
export default employees;
