const projets = [
    {
        id: 0,
        nom: "innovation",
        hs: 3,
        entreeHs: "11:11",
        Date: "20/06/2019",
        place: "ferme",
        superviseur: "flanx",
        etatValidation: false,
        travailEffectue: "une tache1",
    },
    {
        id: 1,
        nom: "innovation",
        hs: 3,
        entreeHs: "11:05",
        Date: "20/06/2019",
        place: "Hors-site",
        superviseur: "flany",
        etatValidation: true,
        travailEffectue: "une tache2",
    },
    {
        id: 2,
        nom: "innovation",
        hs: 2,
        entreeHs: "08:05",
        Date: "20/06/2017",
        place: "derme",
        superviseur: "flanz",
        etatValidation: "enCours",
        travailEffectue: "une tache3",
    },
];
export default projets;
